package br.com.original.opbk.repository;

public enum EnumTransactionQueries {
	GET_TRANSACTION_HISTORY_SELECT("SELECT \n" +
			"'BANCO ORIGINAL S.A' AS NOM_MARCA_PARTC,\n" +
			" '92894922000108' AS NUM_CAD_INSTC_FINCR,\n" +
			" SA.ACCOUNT_TYPE AS ACCOUNT_TYPE,\n" +
			" TH.PURE_ACTION AS PURE_ACTION, \n" +
			" C.BRANCH  AS AG_CTA, \n" +
			" TH.REFERENCE_NUMBER AS NUM_TRANS_CTA,\n" +
			" 'TRANSACAO_EFETIVADA' AS NOM_TPO_CONCL_TRANS,\n" +
			" CDPO.DES_CONTD_PRODT AS NOM_TRANS,\n" +
			" CDPO.DES_CONTD_OPBK AS NOM_TPO_TRANS,\n" +
			" TH.AMOUNT AS VAL_TRANS,\n" +
			" TH.IMPUTATION_TIME AS HOR_TRANS,\n" +
			" C.OPERATION_ID AS NUM_CTA,\n" +
			" TD.TARGET_IDENTIFICATION_NUMBER AS TARGET_IDENTIFICATION_NUMBER,\n" +
			" TD.TARGET_ENTITY AS TARGET_ENTITY,\n" +
			" TD.TARGET_BRANCH AS TARGET_BRANCH,\n" +
			" TD.TARGET_ACCOUNT AS TARGET_ACCOUNT,\n" +
			" TD1.ORIGIN_IDENTIFICATION_NUMBER AS ORIGIN_IDENTIFICATION_NUMBER,\n" +
			" TD1.ORIGIN_ENTITY AS ORIGIN_ENTITY,\n" +
			" TD1.ORIGIN_BRANCH AS ORIGIN_BRANCH,\n" +
			" TD1.ORIGIN_ACCOUNT AS ORIGIN_ACCOUNT,\n" +
			" NULL AS IND_REG_ATIVO,  \n" +
			" NULL AS COD_MOEDA_TRANS, \n" +
			" TH.TRANSACTION_REASON AS TRANSACTION_REASON, \n"+
			" TH.\"ID\" AS ID_HIST, \n" +
			" TH.IMPUTATION_TIME IMPUTATION_TIME"
	),
	GET_TRANSACTION_HISTORY_FROM(" FROM OPBK.R_TXN_HIST TH\n" +
			"INNER JOIN OPBK.R_ACCOUNT C ON (C.ID = TH.ACCOUNT AND C.STATUS = 7 )\n" +
			"INNER JOIN OPBK.R_SUBPRODUCT_ACCOUNT SA ON sa.subproduct = C.SUBPRODUCT AND SA.ACCOUNT_TYPE IN (46,51,109,149)\n" +
			"LEFT JOIN OPBK.R_TRANSACTION_DETAIL TD ON TD.TARGET_REFERENCE_NUMBER  =  TH.REFERENCE_NUMBER \n" +
			"LEFT JOIN OPBK.R_TRANSACTION_DETAIL TD1 ON TD1.ORIGIN_REFERENCE_NUMBER  =  TH.REFERENCE_NUMBER\n" +
			"LEFT JOIN OPBK.CONVS_DOMNO_PRODT_OPBK CDPO ON\n" +
			" (TH.TRANSACTION_REASON = CDPO.IDTFD_FIS_PRODT AND " +
			" CDPO.NOM_TBELA_PRODT  = 'cyberbank_core.transaction_reason'  " +
			" AND  CDPO.NOM_ATRIB_PRODT = 'short_desc') \n"),

	GET_TRANSACTION_HISTORY_WHERE(" WHERE th.IMPUTATION_TIME >= :DATE_BEGIN_TRANSACTION " +
			" AND th.IMPUTATION_TIME <= :DATE_END_TRANSACTION " +
			""),

	INSERT_TRANSACTION("INSERT INTO OPBK.CTA_TRANS_REALZ_FUTUR " +
			" (NOM_MARCA_PARTC," +
			"  NUM_CAD_INSTC_FINCR," +
			"  NOM_TPO_CTA," +
			"  COD_AG,  " +
			"  NUM_TRANS_CTA, " +
			"  NOM_TPO_CONCL_TRANS," +
			"  NOM_TPO_LCTO, " +
			"  NOM_TRANS, " +
			"  NOM_TPO_TRANS, " +
			"  VAL_TRANS, " +
			"  HOR_TRANS," +
			"  NUM_CTA, " +
			"  NUM_CAD_PSSOA_ENVOL," +
			"  NOM_TPO_PSSOA_ENVOL, " +
			"  COD_INSTC_ENVOL, " +
			"  COD_AG_ENVOL, " +
			"  NUM_CTA_ENVOL, " +
			"  NUM_DIGTO_CTA_ENVOL, " +
			"  IND_REG_ATIVO, " +
			"  COD_MOEDA_TRANS," +
			"  NOM_TBELA_ORIGE_TRANS," +
			"  IDTFD_TRANS_TBELA_ORIGE" +
			")" +
			"VALUES              " +
			" (:NOM_MARCA_PARTC," +
			"  :NUM_CAD_INSTC_FINCR," +
			"  :NOM_TPO_CTA," +
			"  :AG_CTA,  " +
			"  OPBK.CTA_TRANS_REALZ_FUTUR_SEQ.NEXTVAL, " +
			"  :NOM_TPO_CONCL_TRANS," +
			"  :NOM_TPO_LCTO, " +
			"  :NOM_TRANS, " +
			"  :NOM_TPO_TRANS, " +
			"  :VAL_TRANS, " +
			"  :HOR_TRANS," +
			"  :NUM_CTA, " +
			"  :NUM_CAD_PSSOA_ENVOL," +
			"  :NOM_TPO_PSSOA_ENVOL, " +
			"  :COD_INSTC_ENVOL, " +
			"  :COD_AG_ENVOL, " +
			"  :ENVOL_NUM_CTA, " +
			"  :NUM_DIGTO_CTA_ENVOL, " +
			"  :IND_REG_ATIVO, " +
			"  :COD_MOEDA_TRANS," +
			"  :NOM_TBELA_ORIGE_TRANS," +
			"  :IDTFD_TRANS_TBELA_ORIGE" +
			")"

	),

	INSERT_RECUSA(
			"INSERT INTO\n" +
					" OPBK.RCUSA_MOTOR_DADOS (" +
					" HOR_INCL_RCUSA,\n" +
					" NOM_TBELA_ORIGE_RCUSA,\n" +
					" DES_ORIGE_RCUSA,\n" +
					" DES_PROCS_RCUSA,\n" +
					" DES_OBJET_RCUSA,\n" +
					" NUM_RCUSA,\n" +
					" COD_TPO_SIT,\n" +
					" COD_LOGIN_USUAR_ATULZ)\n" +
					" VALUES\n" +
					" (:HOR_INCL_RCUSA,\n" +
					" :NOM_TBELA_ORIGE_RCUSA,\n" +
					" :DES_ORIGE_RCUSA,\n" +
					" :DES_PROCS_RCUSA,\n" +
					" :DES_OBJET_RCUSA,\n" +
					" OPBK.RCUSA_MOTOR_DADOS_SEQ.NEXTVAL,\n" +
					" :COD_TPO_SIT,\n" +
					" :COD_LOGIN_USUAR_ATULZ)");
	
	private String query;
	
	private EnumTransactionQueries(String query) {
		this.query = query;
	}
	
	public String getQuery() {
		return this.query;
	}
}
